@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor #FFFFFF

Class Reminder {
    reminderName: String
    reminderDate: Date
}

AddressBook *-right-> "1" UniqueApplicationList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueApplicationList
UniqueTagList -[hidden]down- UniqueApplicationList

UniqueTagList -right-> "*" Tag
UniqueApplicationList -right-> Application

Application -up-> "*" Tag

Application *--> "1" Name
Application *--> "1" Role
Application *--> "0...1" Phone
Application *--> "0...1" Email
Application *--> "0...1" Address
Application *--> "1" Status
Application *--> "0...1" Date
Application *--> "0...1" Reminder
@enduml
