@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor #FFFFFF

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueApplicationList
Class Application
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Role
Class Date
Class Status
Class Reminder {
    reminderName: String
    reminderDate: Date
}

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueApplicationList
UniqueApplicationList --> "~* all" Application
Application *--> "1" Name
Application *--> "1" Role
Application *--> "0...1" Phone
Application *--> "0...1" Email
Application *--> "0...1" Address
Application *--> "1" Status
Application *--> "0...1"Date
Application *--> "*" Tag
Application *--> "0...1" Reminder

Application -[hidden]up--> I
UniqueApplicationList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Tag
Tag -[hidden]right-> Role
Role -[hidden]right-> Status
Status -[hidden]right-> Date
Date -[hidden]right-> Reminder

ModelManager --> "~* filtered" Application
@enduml
